### ISSUE TITLE
Encounter problems about gradle

### ISSUE THREAD

**Issue by mine41** [mikelkarma/Meterpreter-Android#3]
Always Gradle project sync failed.
I wanna know which version of Android Studio should to be used?
or other solutions?

**Comment by mikelkarma** [comment]
I didn't use Android Studio, I did it on my cell phone with Aide Pro

https://github.com/LGLTeam/AIDE-Mods

**Comment by mine41** [comment]
> I didn't use Android Studio, I did it on my cell phone with Aide Pro
> 
> https://github.com/LGLTeam/AIDE-Mods

Thank you very much, I've solved that problem, now I can get MainNous.

But I run this MainNous in my mobilephone, encountered the error "this app is for older version of Android, cannot run properly", just like android/meterpreter/reverse_tcp broken in MSF6.

I've try two cellphones:
Redmi K40, OS: MIUI 13.0.7
TD Tech M40, OS:12.00183(C00E175R2P10)

**Comment by mine41** [comment]
> > I didn't use Android Studio, I did it on my cell phone with Aide Pro
> > https://github.com/LGLTeam/AIDE-Mods
> 
> Thank you very much, I've solved that problem, now I can get MainNous.
> 
> But I run this MainNous in my mobilephone, encountered the error "this app is for older version of Android, cannot run properly", just like android/meterpreter/reverse_tcp broken in MSF6.
> 
> I've try two cellphones: Redmi K40, OS: MIUI 13.0.7 TD Tech M40, OS:12.00183(C00E175R2P10)

Sorry, I found it turns out that even if this error is reported, it can still run normally in the background.

I have implemented a reverse TCP connection to MSF. Thank you for everything you have done
